name: CD

on:
  workflow_run:
    workflows: CI
    types: completed
    branches: main

jobs:
  distribute:
    name: 🛩️ Deliver project
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v2

      - name: 💽 Build OCI image
        run: make build/prod
