name: CD

on:
  push:
    branches:
      - main

jobs:
  distribute:
    name: 🛩️ Deliver project
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v2

      - name: 💽 Build OCI image
        run: make build/prod
