name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: 🧑‍🔬 Test project
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v2

      - name: 📥 Install dependencies
        run: npm install

      - name: 🧪 Run the tests
        run: npm run test
